/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface CheesecakePortalInterface extends ethers.utils.Interface {
  functions: {
    "getAllCheesecakes()": FunctionFragment;
    "getCakeCount()": FunctionFragment;
    "owner()": FunctionFragment;
    "sendCheesecake(string,string,uint256)": FunctionFragment;
    "throwError()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAllCheesecakes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCakeCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sendCheesecake",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "throwError",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllCheesecakes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCakeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendCheesecake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "throwError", data: BytesLike): Result;

  events: {
    "NewCheesecake(string,string,uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewCheesecake"): EventFragment;
}

export type NewCheesecakeEvent = TypedEvent<
  [string, string, BigNumber, string, BigNumber] & {
    name: string;
    message: string;
    cakeSize: BigNumber;
    from: string;
    timestamp: BigNumber;
  }
>;

export class CheesecakePortal extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CheesecakePortalInterface;

  functions: {
    getAllCheesecakes(
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, string, BigNumber, string, BigNumber] & {
          name: string;
          message: string;
          cakeSize: BigNumber;
          giver: string;
          timestamp: BigNumber;
        })[]
      ]
    >;

    getCakeCount(
      overrides?: CallOverrides
    ): Promise<[[BigNumber, BigNumber, BigNumber]]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    sendCheesecake(
      _message: string,
      _name: string,
      _cakeSize: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    throwError(overrides?: CallOverrides): Promise<[void]>;
  };

  getAllCheesecakes(
    overrides?: CallOverrides
  ): Promise<
    ([string, string, BigNumber, string, BigNumber] & {
      name: string;
      message: string;
      cakeSize: BigNumber;
      giver: string;
      timestamp: BigNumber;
    })[]
  >;

  getCakeCount(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, BigNumber]>;

  owner(overrides?: CallOverrides): Promise<string>;

  sendCheesecake(
    _message: string,
    _name: string,
    _cakeSize: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  throwError(overrides?: CallOverrides): Promise<void>;

  callStatic: {
    getAllCheesecakes(
      overrides?: CallOverrides
    ): Promise<
      ([string, string, BigNumber, string, BigNumber] & {
        name: string;
        message: string;
        cakeSize: BigNumber;
        giver: string;
        timestamp: BigNumber;
      })[]
    >;

    getCakeCount(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    owner(overrides?: CallOverrides): Promise<string>;

    sendCheesecake(
      _message: string,
      _name: string,
      _cakeSize: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    throwError(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "NewCheesecake(string,string,uint256,address,uint256)"(
      name?: null,
      message?: null,
      cakeSize?: null,
      from?: string | null,
      timestamp?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, BigNumber],
      {
        name: string;
        message: string;
        cakeSize: BigNumber;
        from: string;
        timestamp: BigNumber;
      }
    >;

    NewCheesecake(
      name?: null,
      message?: null,
      cakeSize?: null,
      from?: string | null,
      timestamp?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, BigNumber],
      {
        name: string;
        message: string;
        cakeSize: BigNumber;
        from: string;
        timestamp: BigNumber;
      }
    >;
  };

  estimateGas: {
    getAllCheesecakes(overrides?: CallOverrides): Promise<BigNumber>;

    getCakeCount(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    sendCheesecake(
      _message: string,
      _name: string,
      _cakeSize: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    throwError(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getAllCheesecakes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCakeCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sendCheesecake(
      _message: string,
      _name: string,
      _cakeSize: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    throwError(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
